### ISSUE TITLE
Running the example according to Lagom's convention(splitting into api and impl)  using Gradle

### ISSUE THREAD

**Issue by pk044** [gmethvin/play-java-lagom-service-example#1]
Hello. I'm sorry if this issue is out of place, I was not sure if there was a better option to contact you.

I tried running the Hello World Lagom example using Gradle, but I can't make it build all of the modules; actually, I can't even get it to build one module.

`model {
    components {
      play {
        platform play: '2.6.9', java: '1.8'
        injectedRoutesGenerator = false

        // reconfigure back to maven layout
        sources {
          java.source.srcDir "hello-api/src/main/java"
          resources.source.srcDir "hello-api/src/main/resources"
        }
      }
    }
  }` 

This code builds only the resource folder, when it reads the classes it gives me a stacktrace saying that dependencies cannot be resolved(i tried putting the dependencies in subprojects{}, allprojects{} - no success).

Could you please point me in the right direction how to handle this? I'd be very grateful.

Thank you in advance.

**Comment by gmethvin** [comment]
I haven't tried it with the gradle plugin, but the api project should not need to be a play project. It can just be a regular library containing the API classes.
